name: processor
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiofiles=0.7.0=pyhd3eb1b0_0
  - aiohttp=3.8.1=py310h7f8727e_1
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - async-timeout=4.0.1=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py310h06a4308_0
  - bs4=4.11.1=hd3eb1b0_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2022.6.15=py310h06a4308_0
  - cffi=1.15.0=py310hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=37.0.2=py310h597c629_0
  - docopt=0.6.2=py_1
  - frozenlist=1.2.0=py310h7f8727e_1
  - idna=3.3=pyhd3eb1b0_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.0.3=h7f8727e_2
  - multidict=5.1.0=py310h7f8727e_2
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1p=h5eee18b_0
  - pip=21.2.4=py310h06a4308_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - python=3.10.4=h12debd9_0
  - python_abi=3.10=2_cp310
  - readline=8.1.2=h7f8727e_1
  - setuptools=61.2.0=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.5=hc218d9a_0
  - stomp.py=8.0.1=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - yarl=1.6.3=py310h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
prefix: /home/kydliceh/.conda/envs/processor
